@baseUrl = http://localhost:5136/sistema

### USUARIO ###

### Registrar Usuário
GET http://localhost:5136/sistema/usuario/registrar

#### Listar Usuários
GET {{baseUrl}}/usuario/listar

#### Consultar Usuario por Email
GET {{baseUrl}}/usuario/buscar/{Email Usuario}

###
GET {{baseUrl}}/usuario/basico/buscarID/3

#### Registrar Usuário
POST {{baseUrl}}/usuario/registrar
Content-Type: application/json

{
    "Nome": "Dayane",
    "Email": "day@gmail.com",
    "Senha": "123456",
    // Campo de perfil será informado futuramente através de um seletor
    // no frontend, não precisando de validação
    "Perfil": "Participante"
}

#### Deletar Usuário
DELETE {{baseUrl}}/usuario/deletar/

#### Atualizar Usuário
PUT {{baseUrl}}/usuario/atualizar/{ID Evento}
Content-Type: application/json

{
    "Nome": "John Chappell",
    "Email": "john_atualizado@gmail.com"
}

### EVENTO ###
#### Listar Eventos
GET {{baseUrl}}/evento/listar

#### Listar Evento por ID
GET {{baseUrl}}/evento/buscar/{ID Evento}

#### Listar Eventos de um Proprietario por ID
GET {{baseUrl}}/evento/meus-eventos/{ID Proprietario}

#### Criar Evento
POST {{baseUrl}}/evento/criar
Content-Type: application/json

{
    "Nome": "Evento 2",
    "Descricao": "Descrição do evento",
    "DataEvento": "2024-12-12T00:00:00",
    "ProprietarioId": 1,
    "VagasMaximo": 1
}

#### Remover Evento
DELETE {{baseUrl}}/evento/excluir/{ID Evento}

#### Editar Evento
PUT {{baseUrl}}/evento/alterar/{ID Evento}
Content-Type: application/json

{
    "Nome": "Evento 2",
    "Descricao": "Descrição do evento",
    "DataEvento": "2024-12-12T00:00:00",
    "VagasMaximo": 1
}

### INSCRIÇÃO
#### Listar inscrições de um evento
GET {{baseUrl}}/evento/listar-inscritos/{ID Evento}

#### Listar inscrições de um usuário
GET {{baseUrl}}/usuario/listar-inscricoes/1

#### Buscar inscrição por Usuario e Evento
GET {{baseUrl}}/usuario/buscar-inscricao/{ID Usuario}/{ID Evento}

#### Inscrever-se em Evento
POST {{baseUrl}}/evento/inscrever
Content-Type: application/json

{
    "EventoId": 1,
    "UsuarioId": 1
}

#### Cancelar Inscrição em Evento
DELETE {{baseUrl}}/evento/cancelar-inscricao/
Content-Type: application/json

{
    "EventoId": 1,
    "UsuarioId": 1
}